language: php

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - cd ..
  - mv boilerplate /tmp/wordpress/wp-content/plugins/
  - cd /tmp/wordpress/wp-content/plugins/boilerplate/

script: phpunit -c phpunit.xml.dist

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=3.8 WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=3.8 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: hhvm-nightly
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: nightly
      env: WP_VERSION=latest WP_MULTISITE=0
  allow_failures:
    - php: hhvm-nightly
    - php: nightly
